version: "3.2"

services:

  fast-login-fn:
    image: functions-fast-login
    build:
      context: ./
      dockerfile: docker/functions/Dockerfile
    env_file: 
      - .env
    environment:
      - languageWorkers__node__arguments=--inspect=0.0.0.0:5858
    working_dir: /usr/src/app
    ports:
      - "7071:7071"
      - "5858:5858"
    networks:
      - io-fn
    depends_on:
      - fnstorage
    volumes:
      - .:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fast-login-fn.rule=Host(`localhost`)"
      - "traefik.http.routers.fast-login-fn.entrypoints=web"
      - "traefik.http.services.fast-login-fn.loadbalancer.server.port=7071"

  fnstorage:
    image: mcr.microsoft.com/azure-storage/azurite:3.9.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - io-fn

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.9.0
    command: ["sh", "-c", "node bin/azurite -l /opt/azurite/folder --blobPort 10003 --queuePort 10004 --tablePort 10005"]
    ports:
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
    depends_on:
      - fnstorage
    networks:
      - io-fn

  cosmosdb:
    image: cosmosdb
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/cosmosdb/Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000
    networks:
      - io-fn

  traefik:
    image: traefik:v2.0
    command: |-
      --entrypoints.web.address=:80
      --providers.docker=true
      --providers.docker.network=io-fn
      --log.level=ERROR
    env_file:
      - .env
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - io-fn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    image: wodby/redis:6-3.15.4
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - io-fn
networks:
  io-fn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
