name: App Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**"
      - "!infra/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-version"
      - "!CODEOWNERS"
      - "!README.md"
    branches:
      - main

jobs:
  code_review:
    uses: pagopa/dx/.github/workflows/legacy_code_review.yaml@main
    name: Code Review
    secrets: inherit
