name: App Code Review

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "**"
      - "!infra/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-version"
      - "!CODEOWNERS"
      - "!README.md"
    branches:
      - main

jobs:
  code_review:
    # uses: pagopa/dx/.github/workflows/legacy_code_review.yaml@main
    name: Code Review
    runs-on: ubuntu-22.04

    steps:

      - name: Check-out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"

      - name: Setup yarn
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Bundle OpenAPI
        run: yarn pregenerate

      - name: Check OpenAPI spec is up-to-date
        run: |
          [[ -z $(git status --porcelain) ]] && exit 0 || git diff && exit 1

      - name: Lint API
        run: yarn lint-api

      - name: Generate definitions
        run: yarn generate

      - name: Unit tests exec
        run: yarn test:coverage
